{extends file="front-end/template.tpl"} 

{block name="content"}


<section id="page-title" class="page-title-center approach-header" style="background-image: url('http://belantara.or.id/wp-content/uploads/PublicationH01_BelantaraFoundation_1920x600px1.jpg')">
<div class="container">
<div class="page-title text-right">
                    <h1 class="text-dark">PRESS RELEASE</h1>
                </div>
            </div>
        </section>
        <!-- end: Page title -->

     <!-- Content -->
        <section id="page-content">
            <div class="container">      
			<h2 style="text-align: center; margin-bottom: 20px;"><strong><span style="color: #99cc00;"><b>Eminent Indonesian Conservationist and Belantara Board Member Receives Lifetime Achievement Award, Has New Species Named After him</b></span></strong></h2>
<p ><img class="img-responsive float-left p-r-20" src="http://belantara.or.id/wp-content/uploads/DSCF9242-copy-e1488434532735.jpg" alt="Professor Jatna Supriatna" width="400" height="400">Jakarta, 1 March 2017 – One of Indonesia’s leading conservation figures and Belantara Foundation’s Vice Chair Of Board of Trustees, <strong>Professor Jatna Supriatna</strong>, has been honoured during a recent event by the environmental non-profit Conservation International (CI) for his long-standing dedication to protect the archipelago’s biodiversity. The Lifetime Achievement Award &amp; Leadership on Biodiversity Conservation recognizes Prof. Supriatna’s significant contributions to the scientific understanding Indonesian primates, and his leadership of the Indonesian programme of CI. Prof. Supriatna’s guidance and experience in the field is helping a new generation of environmental organizations to address the loss of forests and wildlife.</p>
<p><span >During the event, Prof. Supriatna was also given an exceptional honour by the researchers of the Primate Specialist Group of IUCN (International Union for Conservation of Nature) as an appreciation for his dedication in this field, who named a new species of primate they just newly found after him,<i>Tarsius Supriatnai</i>.</span></p>
<p><span style="font-weight: 800; display: block;">“Inspiring and exceptional achievements”</span><br>
<span >“We are thrilled to hear that Prof. Supriatna has received the recognition he deserves for his unwavering commitment to protecting Indonesian nature”, </span><span style="font-weight: 800;">said Agus P. Sari, CEO of Belantara Foundation</span><span >, a non-profit organisation dedicated to the protection of forest and peatland ecosystems. “The entire management of Belantara Foundation and I would like to express our sincere congratulations to Prof. Supriatna, the Vice Chair of our Board of Trustees and a best friend of mine – for this inspiring and exceptional achievement. It reflects the immense contribution made by him as an expert in his field.” </span></p>
<p><span >Reacting to the award, </span><span style="font-weight: 800;">Prof. Supriatna</span><span > said: “I feel so blessed and sincerely surprised by this honour. The award is certainly a result of my consistency in working for biodiversity conservation for 42 years since 1975. I am truly happy that my work is acknowledged, and especially by all of my colleagues who share the same passion with me. I also understand that this is also a big responsibility and a challenge for myself. The drive from all of us is needed to continue fight for conservation.”</span></p>
<p><span style="font-weight: 800; display: block;">A career dedicated to conservation</span><br>
<span >During a career that already spans more than four decades, Prof. Supriatna has chaired the Indonesian chapter of the United Nations Sustainable Development Solutions Network and lead the Indonesia programme of Conservation International. In addition to his role at Belantara Foundation, Prof. Supriatna serves as Chairman of the Research Center for Climate Change, University of Indonesia (RCCC UI). Prof. Supriatna also served as Senior lecturer at the Biology Dept., Director of Biodiversity and Conservation Studies, Coordinator of Graduate Program on Conservation Biology of the University of Indonesia. He has a Master of Science and Doctorate degree from the University of New Mexico, USA, including a pre- and post-doctoral at Columbia University in New York.</span></p>
<hr>
<h2 style="text-align: center; margin-bottom: 20px;"><strong><span style="color: #99cc00;">Belantara Foundation Embarks on Partnership With&nbsp;Climate &amp; Forest Capital To Encourage Private Sector Investment in Indonesia’s Carbon Market</span></strong></h2>
<p>Marrakesh, MOROCCO (November 15, 2016) –Indonesian not-for-profit Belantara Foundation and US based investment firm Climate &amp; Forest Capital agreed to join forces on Tuesday in an effort to explore carbon credit investment opportunities within 10 priority landscapes across Kalimantan and Sumatra.</p>
<p>The partnership, announced on the side of UNFCCC’s COP22 negotiations. comes after a consortium of organizations, including Climate &amp; Forest Capital, launched an investment blueprint for the REDD+ Acceleration Fund (“RAF”).&nbsp; This new financing mechanism is being designed to help combat climate change by getting funds flowing into forest carbon credits, specifically by creating a vehicle which provides investors with enough security to start buying high-quality REDD+ credits.</p>
<p>“This is an exciting time for Belantara Foundation and for Indonesia. Our cooperation with Climate &amp; Forest Capital marks the next phase of our work that will see to the development of blended financing schemes in which co-financing will enable reallocation of risks for interested impact investors.”</p>
<p>“We cannot rely solely on public sector funding if we want to achieve long-term sustainability within Indonesia’s critical landscapes. The private sector needs to play a role in climate finance — it’s time we develop the groundwork to make this happen,” said Agus Sari, Belantara CEO.</p>
<p>Speaking during the MoU signing in Marrakesh, Eron Bloomgarden, a partner at the investment firm, Climate &amp; Forest Capital, explained why Indonesia’s carbon market offers a bounty of potential for private sector investors.</p>
<p>“Curbing global deforestation in Indonesia is crucial to addressing global climate change.&nbsp; We believe economic incentives must change to make trees and forests worth more alive than dead. And we think that payments for REDD+ credits can play an important role in solving global climate change and addressing local deforestation.&nbsp; We are very excited to be exploring this partnership with Belantara Foundation.”</p>
<p>While it’s still early days, Climate &amp; Forest Capital and the other firms behind the REDD+ Acceleration Fund plan to reveal a draft investment blueprint during the COP22 negotiations in Morocco, after which they will publish the blueprint in early 2017. In the meantime Belantara Foundation will investigate potential project partners on the ground,which are producing, or intend to produce, REDD+ credits.</p>
<hr>

			<h2 style="text-align: center;"><strong><span style="color: #99cc00;"><strong>Global Experts Join Indonesian Conservation Foundation</strong></span></strong></h2>
<p></p><center><i><b>Deputy Chair of Indonesian Presidential Task Force on REDD+, Former President of Rainforest<br>
Alliance and UNESCO Ambassador Join Belantara Foundation</b></i></center>&nbsp;<p></p>
<p><strong>Jakarta, 24 May 2016</strong>: The Belantara Foundation today announced that three prominent global&nbsp;experts have come on board to provide proficient leadership and advice to the organization.&nbsp;<strong>Agus Sari</strong>, former Deputy Chair of the Indonesian REDD+ Management Agency, has been&nbsp;appointed as the new Chief Executive Officer for Belantara Foundation while <strong>Tensie Whelan</strong>,&nbsp;former President of Rainforest Alliance and <strong>Dr. Ir. T.A. Fauzi Soelaiman</strong>, Indonesia’s&nbsp;Ambassador to UNESCO, will be joining the Advisory Board in counseling the Foundation on its&nbsp;technical work, partnership development and international promotion strategy.</p>
<p>Agus Sari was the Deputy Chair of the Indonesian REDD+ Management Agency in charge of&nbsp;planning and financing. Prior to that, he was the Chair of Funding Instruments under the&nbsp;Indonesian Presidential Task Force on REDD+ where he led efforts to design a financial and&nbsp;funding mechanism that incentivizes activities related to greenhouse gas emission reduction&nbsp;due to deforestation and forest degradation. A Fulbright Scholar who graduated from&nbsp;University of California (Berkeley, USA) with a degree in Energy and Resources Group, he was&nbsp;previously the Country Director and Regional Policy Director for Ecosecurities, the world’s&nbsp;largest carbon asset development company. Ecosecurities Indonesia, under his leadership, was&nbsp;awarded Asia’s Fastest-Growing Renewable Energy Company by Frost &amp; Sullivan in 2009.</p>
<p>Until 2007, Agus Sari was a member of the Intergovernmental Panel on Climate Change, a&nbsp;Nobel Prize-winning panel and the world’s leading authority on climate change. The former&nbsp;Executive Director of Pelangi, an environmental think-tank, also lectured Environmental Science&nbsp;at the Indonesian Institute of Technology in Serpong, Indonesia as well as Carbon Politics at the&nbsp;Bren School of Environment at the University of California (Santa Barbara, USA).</p>
<p>When announcing the appointment of the new Executive Director, Marzuki Usman, Chair of the&nbsp;Belantara Foundation Board of Trustees and former Indonesian Minister of Forestry, stated,&nbsp;“We are delighted to have Mr. Agus taking the reins for Belantara Foundation and are most&nbsp;certain that with his wealth of knowledge and experience together with his track record and&nbsp;achievements, we are certain he will lead it towards successfully achieving its goals”.</p>
<p>Marzuki further added, “The Belantara Foundation is also most fortunate to have two&nbsp;distinguished colleagues joining our Advisory Board. The commitment by Ms. Whelan and Dr.&nbsp;Fauzi towards sustainability and conservation of natural heritage is renowned and will be most&nbsp;beneficial in providing expert advice to the Foundation’s efforts and initiatives.”</p>
<p>Tensie Whelan is a Clinical Professor of Business and Society, as well as Director of the Center&nbsp;for Sustainable Business at the Stern School of Business, New York University (NYU). She has 25&nbsp;years of experience working on local and international environmental and sustainability issues.&nbsp;During her tenure as President of Rainforest Alliance, she successfully increased the&nbsp;organization’s budget from USD 4.5 million to USD 50 million, which effectively transformed&nbsp;how they engaged with businesses on sustainability issues and recruited 5,000 companies in&nbsp;over 60 countries to work with Rainforest Alliance. She has been recognized by Ethisphere&nbsp;Institute as one of the 100 Most Influential People in Business Ethics, and was the Citi Fellow in&nbsp;Leadership and Ethics at NYU Stern in 2015.</p>
<p>Dr. Ir. T. A. Fauzi Soelaiman is the Ambassador of the Republic of Indonesia to the United&nbsp;Nations Educational, Scientific and Cultural Organization (UNESCO). He has a distinguished&nbsp;career in academia as lecturer and researcher at the Bandung Institute of Technology. Dr. Fauzi&nbsp;is also a prolific scientist with dozens of publications and patents to his name, especially in the field&nbsp;of mechanical engineering. He is a member of the World Energy Council and the Indonesian&nbsp;Renewable Energy Society.</p>
<p>According to Tony Sumampau, Chair of the Belantara Foundation Advisory Board, “The latest&nbsp;addition to our Advisory Board definitely further adds value to our organization. We are certainly&nbsp;looking forward to working alongside Ms. Whelan and Dr. Fauzi to achieve the goals of the&nbsp;Belantara Foundation”.</p>
<p>You can download this press release in pdf <a href="http://belantara.or.id/wp-content/uploads/160524-New-Belantara-CEO-and-Advisory-Board-Members-Announcement-FINAL.pdf" target="_blank"><strong>here</strong></a>.</p>
<p style="text-align: center;"><em>-Ends –</em></p>
<p><strong>About the Belantara Foundation</strong></p>
<p>The Belantara Foundation is dedicated to restoring and protecting rainforests in Sumatra and&nbsp;Kalimantan, Indonesia. Through its work, it aims to balance conserving landscapes, empowering&nbsp;communities and supporting sustainable economic growth. It manages funding and&nbsp;programmes that are designed to safeguard Indonesian natural forests and encourage&nbsp;restoration while also protecting endangered species.</p>
<p>The Foundation was launched at UNFCCC COP21 in Paris in December 2015.</p>
<p>For more information on the Foundation, please visit: www.belantarafoundation.org/</p>
<p><strong>For further information, please contact</strong> :&nbsp;secretariat@belantarafoundation.org</p>
<p>&nbsp;</p>
<hr>
<p>&nbsp;</p>
<h2 style="text-align: center;"><strong><span style="color: #99cc00;">New Foundation to Protect Indonesian Rainforests</span></strong><br>
<strong> <span style="color: #99cc00;">Springs into Action</span></strong></h2>
<p>&nbsp;</p>
<p style="text-align: justify;"><strong>Jakarta, 4 February 2016</strong>: Belantara, the foundation initiated by Asia Pulp &amp; Paper Group (APP) to direct funding and manage programmes to protect Indonesian rainforests is today ready to operate. At a meeting in Jakarta, a newly appointed Advisory Board comprising a group of experts from around the world consisting of widely respected individuals drawn from the government, non-profit and corporate sectors met to officially launch the new foundation.</p>
<p style="text-align: justify;">Belantara will work with communities, civil society, government and businesses to help ensure a careful balance is found between economic development, the livelihoods of people in local communities and environmental conservation. This involves overseeing natural forest restoration and endangered species protection and conducting studies to strengthen sustainable landscape management. In addition, the Foundation will support community empowerment and local economic development, especially in areas that rely heavily on natural resources.</p>
<p style="text-align: justify;">The Foundation, alongside partners including Yapeka, APP and other partners, has produced a landscape conservation master plan to act as a guide for all partner groups implementing projects. With the input of key stakeholders, the foundation has identified ten priority landscapes, where APP and its suppliers have commercial forestry based operations and are among the most ecologically valuable, yet simultaneously threatened in Indonesia. These will form the initial focus of the foundation’s work to support the protection and restoration of local ecosystems while advancing sustainable development within communities. These landscapes are a mix of ecosystems dominated by wetlands, including mangrove forests, peat swamp forests, and freshwater swamp forests, together with lowland rainforests and heath forests.</p>
<p style="text-align: justify;">Marzuki Usman, Chairman of the Board of Trustees for Belantara said, <em>“The landscape approach championed by the Belantara Foundation and APP is vital to the conservation of the ten landscapes we identified in collaboration with our partners. The preservation of one of Indonesia’s most important assets – our rainforests – is of critical importance, today more than ever. Government, private companies and civil society must work together to solve the biggest challenge our country faces.”</em></p>
<p style="text-align: justify;">Jatna Supriatna, Vice Chair of the Board of Trustees for the Foundation added, <em>“These ten priority landscapes are among the most ecologically valuable, yet simultaneously threatened, in Indonesia. Belantara’s mission is to balance the development needs of agriculture, mining and other productive land uses against the critical needs of our environment, so that businesses can prosper while making significant steps in mitigating climate change.”</em></p>
<p style="text-align: justify;">Tony Sumampau, Chair of the newly-assembled Advisory Board to the Belantara Foundation commented, <em>“I am honored to join the advisory board of the Belantara Foundation, which brings together leading academics, administrators and conservationists who have made great advancements in sustainability over their decades of experience. We harbor high hopes for the efforts of the Belantara Foundation – the first platform of its kind – and are tremendously excited to leverage our collective experience in guiding programmes that will protect the ecology and biodiversity of Indonesia’s most important landscapes.”</em></p>
<p style="text-align: justify;">You can download this press release in pdf <a href="http://belantara.or.id/wp-content/uploads/160204_Belantara-Press-Release_final.pdf" target="_blank"><strong>here</strong></a>.</p>
<p style="text-align: center;"><em>– Ends –</em></p>
<p><strong>About the Belantara Foundation</strong><br>
The Belantara Foundation has been initiated by Asia Pulp &amp; Paper Group (APP) to secure and manage funding to support wide-ranging landscape scale conservation projects in Sumatra and Kalimantan, Indonesia. It aims to help ensure a careful balance is found in the region between sustainable economic development, the livelihoods of people in local communities and environmental conservation. This involves overseeing natural forest restoration and endangered species protection, protecting endangered animals, and studies to strengthen sustainable landscape management, as well as engaging in community empowerment and local economic development, especially for those that rely heavily on natural resources.</p>
<p><strong>New Advisory Board Members</strong><br>
• Tony Sumampau, Indonesia<br>
• Tony Juniper, United Kingdom<br>
• Xu Daping, China<br>
• Hans-Jurgen Matern, Germany<br>
• Mark Buckley, United States<br>
• Suzanne Gendron, Hong Kong<br>
• Professor Francesco Bertolini, Italy</p>

            </div>
        </section>
{/block}